#!/bin/bash
#
# Run 'num' tests in parallel to beat up on the lockmgr/pynotify tools.
#
# Each tries to get a lock with 30 second timeout
# Once acquired hold it for 2 seconds before releasing it.
# All should be able to acquire a lock. 
#
# Takes one argument which is the test directory.
# If missing, assume this is run in the test directory.
# 
set -euo pipefail
set -E
trap 'echo "FAILED at line $LINENO: $BASH_COMMAND (exit code $?)" >&2' ERR

if (( $# < 1 )) ; then
    testdir='./'
else
    testdir="$1"
fi

export PYTHONPATH=$(/usr/bin/realpath "$testdir")

#
# Run a few in the background and wait
# for them to exit.
#
num=5
echo " -> test locking using $num processes"

for ((i = 0; i < num; i++)); do
    "$testdir"/test_locks.py "$i" &
    pids+=("$!")
done

#
# wait for each to exit
#
success=0
for pid in "${pids[@]}"; do
    wait "$pid"
    if (( $? == 0 )); then
        success=$(($success + 1))
    fi
done
failed=$((num - success))
echo " test complete"

green() { echo -en "\e[32m$1\e[0m"; }
red()   { echo -en "\e[31m$1\e[0m"; }

if (( success == num )) ; then
    green "[OKAY]"
    echo " Suceeded: $success / $num"
    exit 0
fi
red "[FAIL]" 
echo " Failed: $failed / $num"
exit 1
