#!/usr/bin/bash
#
# Source code checks.
#
# Run in top level dir
# 
# Requires:
# - pylint
# - pycodestyle
# - mypy

mod_dir='src/lockmgr'

export PYTHONPATH=$(/usr/bin/realpath ./src)
    
echo ""
echo "  ... pylint"
/usr/bin/pylint $mod_dir/*py

echo ""
echo "  ... pycodfestyle"
/usr/bin/pycodestyle --max-line-length=110 $mod_dir/*py

echo ""
echo "  ... mypy"
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports $mod_dir

# Tests
echo ""
echo " ... tests"

tdir='src/tests'
/usr/bin/pylint "$tdir"/*py
/usr/bin/pycodestyle --max-line-length=110 "$tdir"/*py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports "$tdir"

