#!/usr/bin/bash
# 
set -euo pipefail
CFLAGS=
LDFLAGS=

meson_opts=(
    setup --reconfigure build/release
    --buildtype=release
)
/usr/bin/meson "${meson_opts[@]}"
/usr/bin/meson compile -C build/release

exit 0
